// portfolioData.ts
import { VideoProject } from "./Portfolio";

export const DEMO_PROJECTS: VideoProject[] = [
  {
    id: 1,
    title: "GP Lubricant Ft. Rashid Khan",
    category: "commercial",
    year: "2024",
    client: "GP Lubricants",
    src: "/assets/portfolioVideos/GP-Lubricant.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    captureAtSeconds: 1.5,
  },
    {
    id: 2,
    title: "Mother Day Ft. Rashid Khan",
    category: "commercial",
    year: "2024",
    client: "Premium Timepieces",
    src: "/assets/portfolioVideos/MotherDay.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    captureAtSeconds: 1.5,
  },
    {
    id: 3,
    title: "Rupeek",
    category: "commercial",
    year: "2024",
    client: "Premium Timepieces",
    src: "/assets/portfolioVideos/Rupeek.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    captureAtSeconds: 1.5,
  },
    {
    id: 4,
    title: "POCO Phone AD Film",
    category: "commercial",
    year: "2024",
    client: "Premium Timepieces",
    src: "/assets/portfolioVideos/POCO.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    captureAtSeconds: 1.5,
  },
    {
    id: 5,
    title: "One Year Promise Ft. Rashid Khan.mp4",
    category: "commercial",
    year: "2024",
    client: "Premium Timepieces",
    src: "/assets/portfolioVideos/OneyearPromise.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    captureAtSeconds: 1.5,
  },

  {
    id: 6,
    title: "Karan Johar",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/KaranJohar.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
    {
    id: 7,
    title: "Jahnvi Kapoor",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/Jahnvi.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
    {
    id: 8,
    title: "Maniesh Paul",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/Manish.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
    {
    id: 9,
    title: "Ranbir Kapoor",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/Ranbir.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
    {
    id: 10,
    title: "Varun Dhawan",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/Varun.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
    {
    id: 11,
    title: "Sara Ali Khan",
    category: "brand",
    year: "2023",
    client: "Filmfare",
    src: "/assets/portfolioVideos/Sara.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Filmfare Awards"],
    captureAtSeconds: 0.8,
  },
  
  {
    id: 12,
    title: "Mere Sath",
    category: "music",
    year: "2023",
    client: "Indie Artist",
    src: "/assets/portfolioVideos/MereSath.mp4",
    description: "Heart-on-sleeve visuals in the pouring rain.",
  },
    {
    id: 13,
    title: "Chand Sa Mukhda",
    category: "music",
    year: "2023",
    client: "Indie Artist",
    src: "/assets/portfolioVideos/ChandsaMukhda.mp4",
    description: "Heart-on-sleeve visuals in the pouring rain.",
  },
    {
    id: 14,
    title: "Music Documentary",
    category: "music",
    year: "2023",
    client: "Sanam Puri",
    src: "/assets/portfolioVideos/SanamPuri.mp4",
    description: "Heart-on-sleeve visuals in the pouring rain.",
  },
    {
    id: 15,
    title: "Taqdeer Awards Teaser",
    category: "brand",
    year: "2023",
    client: "Taqdeer Awards",
    src: "/assets/portfolioVideos/TaqdeerAwards.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    awards: ["Taqdeer Awards"],
    captureAtSeconds: 0.8,
  },
  
  {
    id: 16,
    title: "Neelanath",
    category: "concept",
    year: "2023",
    client: "Art House Production",
    src: "/assets/portfolioVideos/Neelanath.mp4",
    description: "Two strangers, one city, a thousand glances.",
  },
    {
    id: 17,
    title: "Anushka Jolly",
    category: "concept",
    year: "2023",
    client: "Art House Production",
    src: "/assets/portfolioVideos/AnushkaJolly.mp4",
    description: "Two strangers, one city, a thousand glances.",
  },
    {
    id: 18,
    title: "Neelakandan Nair (kalaripayattu)",
    category: "concept",
    year: "2023",
    client: "Art House Production",
    src: "/assets/portfolioVideos/NeelakandanNair(kalaripayattu).mp4",
    description: "Two strangers, one city, a thousand glances.",
  },
  {
    id: 19,
    title: "Amrutt Mission",
    category: "commercial",
    year: "2024",
    client: "GOI",
    src: "/assets/portfolioVideos/AmrutMission.mp4",
    description: "Precision and elegance wrapped in 30 seconds.",
    awards: ["Government of India"],
    captureAtSeconds: 1.5,
  },

  {
    id: 20,
    title: "Sobha Construction Teaser Film",
    category: "brand",
    year: "2023",
    client: "Sobha Construction",
    src: "/assets/portfolioVideos/SobhaConstruction.mp4",
    description: "Momentum, energy, and a bold new brand story.",
    captureAtSeconds: 0.8,
  },

  {
    id: 21,
    title: "Dubai Ambulance Service",
    category: "concept",
    year: "2023",
    client: "",
    src: "/assets/portfolioVideos/DubaiAmbulance.mp4",
    description: "A great service to the community by Dubai Ambulance.",
  },
];
